language: php
php:
  - "5.5"
  - "5.4"
  - "7.0"
  - hhvm

matrix:
    allow_failures:
        - php: 7.0

before_script:
  - composer selfupdate
  - composer install --prefer-source --no-interaction --dev

script: phpunit

after_script:
  - php vendor/bin/coveralls